//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class bEmployee
    {
        public int bId { get; set; }

        [Required(ErrorMessage = "使用者帳號為必填欄位")]
        [DisplayName("使用者帳號")]
        public string bUserId { get; set; }

        [Required(ErrorMessage = "密碼為必填欄位")]
        [DisplayName("密碼")]
        public string bPwd { get; set; }

        [Required(ErrorMessage = "姓名為必填欄位")]
        [DisplayName("姓名")]
        public string bName { get; set; }

        [DisplayName("性別")]
        public int bSex { get; set; }

        [Required(ErrorMessage = "電子郵件為必填欄位")]
        [DisplayName("電子郵件")]
        [EmailAddress(ErrorMessage = "無效的郵件地址")]
        public string bEmail { get; set; }

        [DisplayName("狀態")]
        public int bStatus { get; set; }

        [DisplayName("建立時間")]
        public System.DateTime bCreateTime { get; set; }

        [DisplayName("更新時間")]
        public System.DateTime bUpdateTime { get; set; }
    }
}
