//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class Category
    {
        public int Id { get; set; }

        [DisplayName("分類類型")]
        public int Type { get; set; }

        [DisplayName("排序")]
        public Nullable<int> Sort { get; set; }

        [DisplayName("分類名稱")]
        [Required(ErrorMessage = "請輸入分類名稱")]
        public string Name { get; set; }

        public int State { get; set; }

        [DisplayName("建立時間")]
        public Nullable<System.DateTime> CreateTime { get; set; }

        [DisplayName("更新時間")]
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
