//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tMember
    {
        // public int tId { get; set; }
        //   public string tUserId { get; set; }
        //  public string tPwd { get; set; }
        //  public string tName { get; set; }
        // public string tEmail { get; set; }
        // public Nullable<System.DateTime> bCreateTime { get; set; }
        //public Nullable<System.DateTime> bUpdateTime { get; set; }
        public int tId { get; set; }

        [Required(ErrorMessage = "帳號為必填欄位")]
        [DisplayName("帳號")]
        public string tUserId { get; set; }

        [Required(ErrorMessage = "密碼為必填欄位")]
        [DisplayName("密碼")]
        public string tPwd { get; set; }

        [Required(ErrorMessage = "姓名為必填欄位")]
        [DisplayName("姓名")]
        public string tName { get; set; }

        [Required(ErrorMessage = "電子郵件為必填欄位")]
        [DisplayName("電子郵件")]
        [EmailAddress(ErrorMessage = "無效的郵件地址")]
        public string tEmail { get; set; }

        [DisplayName("建立時間")]
        public System.DateTime bCreateTime { get; set; }

        [DisplayName("更新時間")]
        public System.DateTime bUpdateTime { get; set; }
    }
}
